'use client'

import WeekDots from '@/components/WeekDots'
import BackToTop from '@/components/BackToTop'
import LanguageToggle from '@/components/LanguageToggle'
import { useLanguage } from '@/contexts/LanguageContext'

export default function WeekDetailClient({ week, recentWeeks, currentSlug }) {
  const { language } = useLanguage()

  const t = {
    title: {
      zh: '礼拜观',
      en: 'Frontier Weekly'
    },
    subtitle: {
      zh: '前沿趋势发现与科技热点洞察',
      en: 'Trends Discovery & Idea Insights'
    }
  }

  return (
    <div className="min-h-screen">
      {/* Hero Section - Fixed Title */}
      <section className="pt-20 pb-8 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <h1 
            className="text-4xl sm:text-5xl font-serif font-semibold mb-4 animate-fade-in"
            style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-serif)' }}
          >
            {t.title[language]}
          </h1>
          <p 
            className="text-lg mb-8 animate-fade-in"
            style={{ color: 'var(--text-muted)', animationDelay: '0.1s' }}
          >
            {t.subtitle[language]}
          </p>

          <div className="animate-fade-in" style={{ animationDelay: '0.15s' }}>
            <LanguageToggle />
          </div>
        </div>
      </section>

      {/* Week Navigator - Left Aligned */}
      <section className="px-4 pb-6">
        <div className="max-w-3xl mx-auto">
          <div className="animate-fade-in" style={{ animationDelay: '0.2s' }}>
            <WeekDots weeks={recentWeeks} currentSlug={currentSlug} />
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="pb-20 px-4">
        <div className="max-w-3xl mx-auto">
          <article 
            className="card p-8 sm:p-10 animate-fade-in"
            style={{ animationDelay: '0.3s' }}
          >
            {Array.isArray(week.keywords) && week.keywords.length > 0 && (
              <div className="keyword-row mb-6">
                {week.keywords.map((kw) => (
                  <span key={kw} className="keyword-pill">
                    {kw}
                  </span>
                ))}
              </div>
            )}

            {/* Pure Markdown Content Only */}
            <div 
              className="markdown-content"
              dangerouslySetInnerHTML={{ __html: week.contentHtml }}
            />
          </article>
        </div>
      </section>

      {/* Back to Top */}
      <BackToTop />

      {/* Footer */}
      <footer 
        className="py-8 text-center text-xs"
        style={{ color: 'var(--text-muted)' }}
      >
        <div className="space-y-1">
          {language === 'zh' ? (
            <>
              <p>本内容由领域记忆驱动的研究型内容生产工作流生成</p>
              <p>联系作者：xuhaoruins@hotmail.com</p>
            </>
          ) : (
            <>
              <p>Content generated by memory-based research-driven Agentic workflow.</p>
              <p>Contact Author: xuhaoruins@hotmail.com</p>
            </>
          )}
          <p className="pt-1">© {new Date().getFullYear()} {language === 'en' ? 'Frontier Weekly' : '礼拜观'}</p>
        </div>
      </footer>
    </div>
  )
}
