'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import WeekDots from '@/components/WeekDots'
import LanguageToggle from '@/components/LanguageToggle'
import { useLanguage } from '@/contexts/LanguageContext'

export default function HomeContent({ latestWeek, recentWeeks }) {
  const { language } = useLanguage()
  const pathname = usePathname() || '/'
  const isEn = pathname === '/en' || pathname.startsWith('/en/')
  const prefix = isEn ? '/en' : ''

  const t = {
    title: {
      zh: '礼拜观',
      en: 'Frontier Weekly'
    },
    subtitle: {
      zh: '前沿趋势发现与科技热点洞察',
      en: 'Trends Discovery & Idea Insights'
    },
    archives: {
      zh: '查看全部周报',
      en: 'View All Briefs'
    },
    noContent: {
      zh: '暂无内容，敬请期待',
      en: 'Content coming soon'
    }
  }

  return (
    <div className="min-h-screen">
      {/* Hero Section - Fixed Title */}
      <section className="pt-20 pb-8 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <h1 
            className="text-4xl sm:text-5xl font-serif font-semibold mb-4 animate-fade-in"
            style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-serif)' }}
          >
            {t.title[language]}
          </h1>
          <p 
            className="text-lg mb-8 animate-fade-in"
            style={{ color: 'var(--text-muted)', animationDelay: '0.1s' }}
          >
            {t.subtitle[language]}
          </p>

          <div className="animate-fade-in" style={{ animationDelay: '0.15s' }}>
            <LanguageToggle />
          </div>
        </div>
      </section>

      {/* Week Navigator - Left Aligned */}
      <section className="px-4 pb-6">
        <div className="max-w-3xl mx-auto">
          {recentWeeks.length > 0 && (
            <div className="animate-fade-in" style={{ animationDelay: '0.2s' }}>
              <WeekDots weeks={recentWeeks} currentSlug={latestWeek?.slug} />
            </div>
          )}
        </div>
      </section>

      {/* Main Content - Pure Markdown */}
      <section className="pb-20 px-4">
        <div className="max-w-3xl mx-auto">
          {latestWeek ? (
            <article 
              className="card p-8 sm:p-10 animate-fade-in"
              style={{ animationDelay: '0.3s' }}
            >
              {Array.isArray(latestWeek.keywords) && latestWeek.keywords.length > 0 && (
                <div className="keyword-row mb-6">
                  {latestWeek.keywords.map((kw) => (
                    <span key={kw} className="keyword-pill">
                      {kw}
                    </span>
                  ))}
                </div>
              )}

              {/* Pure Markdown Content Only */}
              {latestWeek.contentHtml && (
                <div 
                  className="markdown-content"
                  dangerouslySetInnerHTML={{ __html: latestWeek.contentHtml }}
                />
              )}
            </article>
          ) : (
            <div 
              className="text-center py-20"
              style={{ color: 'var(--text-muted)' }}
            >
              {t.noContent[language]}
            </div>
          )}

          {/* Archives Link */}
          {recentWeeks.length > 1 && (
            <div className="text-center mt-12 animate-fade-in" style={{ animationDelay: '0.4s' }}>
              <Link 
                href={`${prefix}/archives`}
                className="inline-flex items-center px-5 py-2.5 rounded-full text-sm font-medium transition-all duration-200 hover:scale-105"
                style={{
                  background: 'var(--bg-card)',
                  border: '1px solid var(--border)',
                  color: 'var(--text-secondary)'
                }}
              >
                {t.archives[language]}
              </Link>
            </div>
          )}
        </div>
      </section>

      {/* Footer */}
      <footer 
        className="py-8 text-center text-xs"
        style={{ color: 'var(--text-muted)' }}
      >
        <div className="space-y-1">
          {language === 'zh' ? (
            <>
              <p>本内容由领域记忆驱动的研究型内容生产工作流生成</p>
              <p>联系作者：xuhaoruins@hotmail.com</p>
            </>
          ) : (
            <>
              <p>Content generated by memory-based research-driven Agentic workflow.</p>
              <p>Contact Author: xuhaoruins@hotmail.com</p>
            </>
          )}
          <p className="pt-1">© {new Date().getFullYear()} {language === 'en' ? 'Frontier Weekly' : '礼拜观'}</p>
        </div>
      </footer>
    </div>
  )
}
